# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Unity - Builder
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-builder@c317d144c37b2004ae02490988ded7b934a182be
        uses: game-ci/unity-builder@v2.0-alpha-13
        with:
          # Version of unity to use for building the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt
          unityVersion: 2020.3.21f1 # optional, default is auto
          # Platform that the build should target.
          targetPlatform: webGL# optional, default is 
          # Relative path to the project to be built.
          #projectPath: # optional, default is 
          # Name of the build.
          #buildName: # optional, default is 
          # Path where the builds should be stored.
          #buildsPath: # optional, default is 
          
